let nama = "Maylani";
let usia = 20;
let tinggi = 155;
let bilangan1 = 9;
let bilangan2 = 2;
let bilangan3 = 19;
let isMahasiswa = true;
let isMahasiswa1 = false;
console.log(isMahasiswa1);
console.log(isMahasiswa);
console.log("hasil penjumlahan =", bilangan1 + bilangan2);
console.log("hasil pengurangan=", bilangan2 - bilangan3);
console.log("usia dan tinggi=", usia * tinggi);
